// Generated by gencpp from file laser/warning.msg
// DO NOT EDIT!


#ifndef LASER_MESSAGE_WARNING_H
#define LASER_MESSAGE_WARNING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser
{
template <class ContainerAllocator>
struct warning_
{
  typedef warning_<ContainerAllocator> Type;

  warning_()
    : warning()  {
    }
  warning_(const ContainerAllocator& _alloc)
    : warning(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _warning_type;
  _warning_type warning;




  typedef boost::shared_ptr< ::laser::warning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser::warning_<ContainerAllocator> const> ConstPtr;

}; // struct warning_

typedef ::laser::warning_<std::allocator<void> > warning;

typedef boost::shared_ptr< ::laser::warning > warningPtr;
typedef boost::shared_ptr< ::laser::warning const> warningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser::warning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser::warning_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'laser': ['/home/turtlebot2/xu_slam/src/laser/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser::warning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser::warning_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser::warning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser::warning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser::warning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser::warning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser::warning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd40b7d5c92cc8716f9a8241b06333cd";
  }

  static const char* value(const ::laser::warning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd40b7d5c92cc871ULL;
  static const uint64_t static_value2 = 0x6f9a8241b06333cdULL;
};

template<class ContainerAllocator>
struct DataType< ::laser::warning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser/warning";
  }

  static const char* value(const ::laser::warning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser::warning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string warning\n\
";
  }

  static const char* value(const ::laser::warning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser::warning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.warning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct warning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser::warning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser::warning_<ContainerAllocator>& v)
  {
    s << indent << "warning: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.warning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_MESSAGE_WARNING_H
