// Generated by gencpp from file voice_interface/Send.msg
// DO NOT EDIT!


#ifndef VOICE_INTERFACE_MESSAGE_SEND_H
#define VOICE_INTERFACE_MESSAGE_SEND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_interface
{
template <class ContainerAllocator>
struct Send_
{
  typedef Send_<ContainerAllocator> Type;

  Send_()
    : send(false)
    , song1(0)
    , object1(0)
    , dao1(0)
    , dd(0)
    , rencheng1(0)  {
    }
  Send_(const ContainerAllocator& _alloc)
    : send(false)
    , song1(0)
    , object1(0)
    , dao1(0)
    , dd(0)
    , rencheng1(0)  {
    }



   typedef uint8_t _send_type;
  _send_type send;

   typedef int64_t _song1_type;
  _song1_type song1;

   typedef int64_t _object1_type;
  _object1_type object1;

   typedef int64_t _dao1_type;
  _dao1_type dao1;

   typedef int64_t _dd_type;
  _dd_type dd;

   typedef int64_t _rencheng1_type;
  _rencheng1_type rencheng1;




  typedef boost::shared_ptr< ::voice_interface::Send_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_interface::Send_<ContainerAllocator> const> ConstPtr;

}; // struct Send_

typedef ::voice_interface::Send_<std::allocator<void> > Send;

typedef boost::shared_ptr< ::voice_interface::Send > SendPtr;
typedef boost::shared_ptr< ::voice_interface::Send const> SendConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_interface::Send_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_interface::Send_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'voice_interface': ['/home/turtlebot2/xu_slam/src/voice_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_interface::Send_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_interface::Send_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_interface::Send_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_interface::Send_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_interface::Send_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_interface::Send_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_interface::Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a711c708becf295f2e6df4e6e308b5bd";
  }

  static const char* value(const ::voice_interface::Send_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa711c708becf295fULL;
  static const uint64_t static_value2 = 0x2e6df4e6e308b5bdULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_interface::Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_interface/Send";
  }

  static const char* value(const ::voice_interface::Send_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_interface::Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool send\n\
int64 song1\n\
int64 object1\n\
int64 dao1\n\
int64 dd\n\
int64 rencheng1\n\
\n\
";
  }

  static const char* value(const ::voice_interface::Send_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_interface::Send_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.send);
      stream.next(m.song1);
      stream.next(m.object1);
      stream.next(m.dao1);
      stream.next(m.dd);
      stream.next(m.rencheng1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Send_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_interface::Send_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_interface::Send_<ContainerAllocator>& v)
  {
    s << indent << "send: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.send);
    s << indent << "song1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.song1);
    s << indent << "object1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.object1);
    s << indent << "dao1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dao1);
    s << indent << "dd: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dd);
    s << indent << "rencheng1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.rencheng1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_INTERFACE_MESSAGE_SEND_H
