// Generated by gencpp from file voice_interface/Transmit.msg
// DO NOT EDIT!


#ifndef VOICE_INTERFACE_MESSAGE_TRANSMIT_H
#define VOICE_INTERFACE_MESSAGE_TRANSMIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_interface
{
template <class ContainerAllocator>
struct Transmit_
{
  typedef Transmit_<ContainerAllocator> Type;

  Transmit_()
    : transmit(false)
    , object(0)
    , didian(0)  {
    }
  Transmit_(const ContainerAllocator& _alloc)
    : transmit(false)
    , object(0)
    , didian(0)  {
    }



   typedef uint8_t _transmit_type;
  _transmit_type transmit;

   typedef int64_t _object_type;
  _object_type object;

   typedef int64_t _didian_type;
  _didian_type didian;




  typedef boost::shared_ptr< ::voice_interface::Transmit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_interface::Transmit_<ContainerAllocator> const> ConstPtr;

}; // struct Transmit_

typedef ::voice_interface::Transmit_<std::allocator<void> > Transmit;

typedef boost::shared_ptr< ::voice_interface::Transmit > TransmitPtr;
typedef boost::shared_ptr< ::voice_interface::Transmit const> TransmitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_interface::Transmit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_interface::Transmit_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voice_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'voice_interface': ['/home/turtlebot2/xu_slam/src/voice_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voice_interface::Transmit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_interface::Transmit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_interface::Transmit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_interface::Transmit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_interface::Transmit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_interface::Transmit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_interface::Transmit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99c7f83694b9f3c2c39a66d868b1bbeb";
  }

  static const char* value(const ::voice_interface::Transmit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99c7f83694b9f3c2ULL;
  static const uint64_t static_value2 = 0xc39a66d868b1bbebULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_interface::Transmit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_interface/Transmit";
  }

  static const char* value(const ::voice_interface::Transmit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_interface::Transmit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool transmit\n\
int64 object\n\
int64 didian\n\
";
  }

  static const char* value(const ::voice_interface::Transmit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_interface::Transmit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transmit);
      stream.next(m.object);
      stream.next(m.didian);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Transmit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_interface::Transmit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_interface::Transmit_<ContainerAllocator>& v)
  {
    s << indent << "transmit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transmit);
    s << indent << "object: ";
    Printer<int64_t>::stream(s, indent + "  ", v.object);
    s << indent << "didian: ";
    Printer<int64_t>::stream(s, indent + "  ", v.didian);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_INTERFACE_MESSAGE_TRANSMIT_H
