// Generated by gencpp from file robot_status/launch_amclRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_STATUS_MESSAGE_LAUNCH_AMCLREQUEST_H
#define ROBOT_STATUS_MESSAGE_LAUNCH_AMCLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_status
{
template <class ContainerAllocator>
struct launch_amclRequest_
{
  typedef launch_amclRequest_<ContainerAllocator> Type;

  launch_amclRequest_()
    : start()  {
    }
  launch_amclRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_type;
  _start_type start;




  typedef boost::shared_ptr< ::robot_status::launch_amclRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_status::launch_amclRequest_<ContainerAllocator> const> ConstPtr;

}; // struct launch_amclRequest_

typedef ::robot_status::launch_amclRequest_<std::allocator<void> > launch_amclRequest;

typedef boost::shared_ptr< ::robot_status::launch_amclRequest > launch_amclRequestPtr;
typedef boost::shared_ptr< ::robot_status::launch_amclRequest const> launch_amclRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_status::launch_amclRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_status::launch_amclRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_status

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'robot_status': ['/home/turtlebot2/xu_slam/src/robot_status/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_status::launch_amclRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_status::launch_amclRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_status::launch_amclRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_status::launch_amclRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_status::launch_amclRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_status::launch_amclRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_status::launch_amclRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34ede85548daeef03201b4a532fb98e1";
  }

  static const char* value(const ::robot_status::launch_amclRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34ede85548daeef0ULL;
  static const uint64_t static_value2 = 0x3201b4a532fb98e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_status::launch_amclRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_status/launch_amclRequest";
  }

  static const char* value(const ::robot_status::launch_amclRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_status::launch_amclRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string start\n\
";
  }

  static const char* value(const ::robot_status::launch_amclRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_status::launch_amclRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct launch_amclRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_status::launch_amclRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_status::launch_amclRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_STATUS_MESSAGE_LAUNCH_AMCLREQUEST_H
