// Generated by gencpp from file robot_status/launch_amcl.msg
// DO NOT EDIT!


#ifndef ROBOT_STATUS_MESSAGE_LAUNCH_AMCL_H
#define ROBOT_STATUS_MESSAGE_LAUNCH_AMCL_H

#include <ros/service_traits.h>


#include <robot_status/launch_amclRequest.h>
#include <robot_status/launch_amclResponse.h>


namespace robot_status
{

struct launch_amcl
{

typedef launch_amclRequest Request;
typedef launch_amclResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct launch_amcl
} // namespace robot_status


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_status::launch_amcl > {
  static const char* value()
  {
    return "fa28e77b8a1dcde11cf9b68339ca8216";
  }

  static const char* value(const ::robot_status::launch_amcl&) { return value(); }
};

template<>
struct DataType< ::robot_status::launch_amcl > {
  static const char* value()
  {
    return "robot_status/launch_amcl";
  }

  static const char* value(const ::robot_status::launch_amcl&) { return value(); }
};


// service_traits::MD5Sum< ::robot_status::launch_amclRequest> should match 
// service_traits::MD5Sum< ::robot_status::launch_amcl > 
template<>
struct MD5Sum< ::robot_status::launch_amclRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_status::launch_amcl >::value();
  }
  static const char* value(const ::robot_status::launch_amclRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_status::launch_amclRequest> should match 
// service_traits::DataType< ::robot_status::launch_amcl > 
template<>
struct DataType< ::robot_status::launch_amclRequest>
{
  static const char* value()
  {
    return DataType< ::robot_status::launch_amcl >::value();
  }
  static const char* value(const ::robot_status::launch_amclRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_status::launch_amclResponse> should match 
// service_traits::MD5Sum< ::robot_status::launch_amcl > 
template<>
struct MD5Sum< ::robot_status::launch_amclResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_status::launch_amcl >::value();
  }
  static const char* value(const ::robot_status::launch_amclResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_status::launch_amclResponse> should match 
// service_traits::DataType< ::robot_status::launch_amcl > 
template<>
struct DataType< ::robot_status::launch_amclResponse>
{
  static const char* value()
  {
    return DataType< ::robot_status::launch_amcl >::value();
  }
  static const char* value(const ::robot_status::launch_amclResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_STATUS_MESSAGE_LAUNCH_AMCL_H
