// Generated by gencpp from file robot_status/mapdata.msg
// DO NOT EDIT!


#ifndef ROBOT_STATUS_MESSAGE_MAPDATA_H
#define ROBOT_STATUS_MESSAGE_MAPDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>
#include <robot_status/robot_odom.h>

namespace robot_status
{
template <class ContainerAllocator>
struct mapdata_
{
  typedef mapdata_<ContainerAllocator> Type;

  mapdata_()
    : grid()
    , odom()
    , mapnum(0)  {
    }
  mapdata_(const ContainerAllocator& _alloc)
    : grid(_alloc)
    , odom(_alloc)
    , mapnum(0)  {
    }



   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _grid_type;
  _grid_type grid;

   typedef  ::robot_status::robot_odom_<ContainerAllocator>  _odom_type;
  _odom_type odom;

   typedef int32_t _mapnum_type;
  _mapnum_type mapnum;




  typedef boost::shared_ptr< ::robot_status::mapdata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_status::mapdata_<ContainerAllocator> const> ConstPtr;

}; // struct mapdata_

typedef ::robot_status::mapdata_<std::allocator<void> > mapdata;

typedef boost::shared_ptr< ::robot_status::mapdata > mapdataPtr;
typedef boost::shared_ptr< ::robot_status::mapdata const> mapdataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_status::mapdata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_status::mapdata_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_status

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'robot_status': ['/home/turtlebot2/xu_slam/src/robot_status/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_status::mapdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_status::mapdata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_status::mapdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_status::mapdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_status::mapdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_status::mapdata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_status::mapdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd84b02b7e7fa15748f38cf373f42238";
  }

  static const char* value(const ::robot_status::mapdata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd84b02b7e7fa157ULL;
  static const uint64_t static_value2 = 0x48f38cf373f42238ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_status::mapdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_status/mapdata";
  }

  static const char* value(const ::robot_status::mapdata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_status::mapdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/OccupancyGrid grid\n\
robot_status/robot_odom odom\n\
int32 mapnum\n\
\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: robot_status/robot_odom\n\
std_msgs/Header header\n\
geometry_msgs/Point position\n\
geometry_msgs/Quaternion rotation\n\
";
  }

  static const char* value(const ::robot_status::mapdata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_status::mapdata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grid);
      stream.next(m.odom);
      stream.next(m.mapnum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct mapdata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_status::mapdata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_status::mapdata_<ContainerAllocator>& v)
  {
    s << indent << "grid: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.grid);
    s << indent << "odom: ";
    s << std::endl;
    Printer< ::robot_status::robot_odom_<ContainerAllocator> >::stream(s, indent + "  ", v.odom);
    s << indent << "mapnum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mapnum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_STATUS_MESSAGE_MAPDATA_H
