// Generated by gencpp from file utils/CliffEvent.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_CLIFFEVENT_H
#define UTILS_MESSAGE_CLIFFEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct CliffEvent_
{
  typedef CliffEvent_<ContainerAllocator> Type;

  CliffEvent_()
    : LEFT(0)
    , FRONT(0)
    , RIGHT(0)
    , BACK(0)  {
    }
  CliffEvent_(const ContainerAllocator& _alloc)
    : LEFT(0)
    , FRONT(0)
    , RIGHT(0)
    , BACK(0)  {
    }



   typedef uint8_t _LEFT_type;
  _LEFT_type LEFT;

   typedef uint8_t _FRONT_type;
  _FRONT_type FRONT;

   typedef uint8_t _RIGHT_type;
  _RIGHT_type RIGHT;

   typedef uint8_t _BACK_type;
  _BACK_type BACK;




  typedef boost::shared_ptr< ::utils::CliffEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::CliffEvent_<ContainerAllocator> const> ConstPtr;

}; // struct CliffEvent_

typedef ::utils::CliffEvent_<std::allocator<void> > CliffEvent;

typedef boost::shared_ptr< ::utils::CliffEvent > CliffEventPtr;
typedef boost::shared_ptr< ::utils::CliffEvent const> CliffEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::CliffEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::CliffEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'utils': ['/home/turtlebot/xu_slam/src/utils/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::utils::CliffEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::CliffEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::CliffEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::CliffEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::CliffEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::CliffEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::CliffEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4aa84ea193dabb93b5378e5ff8539958";
  }

  static const char* value(const ::utils::CliffEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4aa84ea193dabb93ULL;
  static const uint64_t static_value2 = 0xb5378e5ff8539958ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::CliffEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/CliffEvent";
  }

  static const char* value(const ::utils::CliffEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::CliffEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LEFT\n\
uint8 FRONT\n\
uint8 RIGHT\n\
uint8 BACK\n\
\n\
";
  }

  static const char* value(const ::utils::CliffEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::CliffEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LEFT);
      stream.next(m.FRONT);
      stream.next(m.RIGHT);
      stream.next(m.BACK);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CliffEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::CliffEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::CliffEvent_<ContainerAllocator>& v)
  {
    s << indent << "LEFT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LEFT);
    s << indent << "FRONT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FRONT);
    s << indent << "RIGHT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RIGHT);
    s << indent << "BACK: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BACK);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_CLIFFEVENT_H
