// Generated by gencpp from file facerobot/greeting.msg
// DO NOT EDIT!


#ifndef FACEROBOT_MESSAGE_GREETING_H
#define FACEROBOT_MESSAGE_GREETING_H

#include <ros/service_traits.h>


#include <facerobot/greetingRequest.h>
#include <facerobot/greetingResponse.h>


namespace facerobot
{

struct greeting
{

typedef greetingRequest Request;
typedef greetingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct greeting
} // namespace facerobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::facerobot::greeting > {
  static const char* value()
  {
    return "0bac347fe4d77e1d1284a23a97504d84";
  }

  static const char* value(const ::facerobot::greeting&) { return value(); }
};

template<>
struct DataType< ::facerobot::greeting > {
  static const char* value()
  {
    return "facerobot/greeting";
  }

  static const char* value(const ::facerobot::greeting&) { return value(); }
};


// service_traits::MD5Sum< ::facerobot::greetingRequest> should match 
// service_traits::MD5Sum< ::facerobot::greeting > 
template<>
struct MD5Sum< ::facerobot::greetingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::facerobot::greeting >::value();
  }
  static const char* value(const ::facerobot::greetingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::facerobot::greetingRequest> should match 
// service_traits::DataType< ::facerobot::greeting > 
template<>
struct DataType< ::facerobot::greetingRequest>
{
  static const char* value()
  {
    return DataType< ::facerobot::greeting >::value();
  }
  static const char* value(const ::facerobot::greetingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::facerobot::greetingResponse> should match 
// service_traits::MD5Sum< ::facerobot::greeting > 
template<>
struct MD5Sum< ::facerobot::greetingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::facerobot::greeting >::value();
  }
  static const char* value(const ::facerobot::greetingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::facerobot::greetingResponse> should match 
// service_traits::DataType< ::facerobot::greeting > 
template<>
struct DataType< ::facerobot::greetingResponse>
{
  static const char* value()
  {
    return DataType< ::facerobot::greeting >::value();
  }
  static const char* value(const ::facerobot::greetingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACEROBOT_MESSAGE_GREETING_H
