// Generated by gencpp from file facerobot/sound_synthesisRequest.msg
// DO NOT EDIT!


#ifndef FACEROBOT_MESSAGE_SOUND_SYNTHESISREQUEST_H
#define FACEROBOT_MESSAGE_SOUND_SYNTHESISREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace facerobot
{
template <class ContainerAllocator>
struct sound_synthesisRequest_
{
  typedef sound_synthesisRequest_<ContainerAllocator> Type;

  sound_synthesisRequest_()
    : name()  {
    }
  sound_synthesisRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::facerobot::sound_synthesisRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::facerobot::sound_synthesisRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sound_synthesisRequest_

typedef ::facerobot::sound_synthesisRequest_<std::allocator<void> > sound_synthesisRequest;

typedef boost::shared_ptr< ::facerobot::sound_synthesisRequest > sound_synthesisRequestPtr;
typedef boost::shared_ptr< ::facerobot::sound_synthesisRequest const> sound_synthesisRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::facerobot::sound_synthesisRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace facerobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'voice_msg': ['/home/turtlebot/xu_slam/src/voice_msg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::facerobot::sound_synthesisRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facerobot::sound_synthesisRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facerobot::sound_synthesisRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::facerobot::sound_synthesisRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "facerobot/sound_synthesisRequest";
  }

  static const char* value(const ::facerobot::sound_synthesisRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
\n\
";
  }

  static const char* value(const ::facerobot::sound_synthesisRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct sound_synthesisRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::facerobot::sound_synthesisRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::facerobot::sound_synthesisRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACEROBOT_MESSAGE_SOUND_SYNTHESISREQUEST_H
