// Generated by gencpp from file facerobot/sound_synthesis.msg
// DO NOT EDIT!


#ifndef FACEROBOT_MESSAGE_SOUND_SYNTHESIS_H
#define FACEROBOT_MESSAGE_SOUND_SYNTHESIS_H

#include <ros/service_traits.h>


#include <facerobot/sound_synthesisRequest.h>
#include <facerobot/sound_synthesisResponse.h>


namespace facerobot
{

struct sound_synthesis
{

typedef sound_synthesisRequest Request;
typedef sound_synthesisResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sound_synthesis
} // namespace facerobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::facerobot::sound_synthesis > {
  static const char* value()
  {
    return "0bac347fe4d77e1d1284a23a97504d84";
  }

  static const char* value(const ::facerobot::sound_synthesis&) { return value(); }
};

template<>
struct DataType< ::facerobot::sound_synthesis > {
  static const char* value()
  {
    return "facerobot/sound_synthesis";
  }

  static const char* value(const ::facerobot::sound_synthesis&) { return value(); }
};


// service_traits::MD5Sum< ::facerobot::sound_synthesisRequest> should match 
// service_traits::MD5Sum< ::facerobot::sound_synthesis > 
template<>
struct MD5Sum< ::facerobot::sound_synthesisRequest>
{
  static const char* value()
  {
    return MD5Sum< ::facerobot::sound_synthesis >::value();
  }
  static const char* value(const ::facerobot::sound_synthesisRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::facerobot::sound_synthesisRequest> should match 
// service_traits::DataType< ::facerobot::sound_synthesis > 
template<>
struct DataType< ::facerobot::sound_synthesisRequest>
{
  static const char* value()
  {
    return DataType< ::facerobot::sound_synthesis >::value();
  }
  static const char* value(const ::facerobot::sound_synthesisRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::facerobot::sound_synthesisResponse> should match 
// service_traits::MD5Sum< ::facerobot::sound_synthesis > 
template<>
struct MD5Sum< ::facerobot::sound_synthesisResponse>
{
  static const char* value()
  {
    return MD5Sum< ::facerobot::sound_synthesis >::value();
  }
  static const char* value(const ::facerobot::sound_synthesisResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::facerobot::sound_synthesisResponse> should match 
// service_traits::DataType< ::facerobot::sound_synthesis > 
template<>
struct DataType< ::facerobot::sound_synthesisResponse>
{
  static const char* value()
  {
    return DataType< ::facerobot::sound_synthesis >::value();
  }
  static const char* value(const ::facerobot::sound_synthesisResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACEROBOT_MESSAGE_SOUND_SYNTHESIS_H
