// Generated by gencpp from file facerobot/voiceRecog.msg
// DO NOT EDIT!


#ifndef FACEROBOT_MESSAGE_VOICERECOG_H
#define FACEROBOT_MESSAGE_VOICERECOG_H

#include <ros/service_traits.h>


#include <facerobot/voiceRecogRequest.h>
#include <facerobot/voiceRecogResponse.h>


namespace facerobot
{

struct voiceRecog
{

typedef voiceRecogRequest Request;
typedef voiceRecogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct voiceRecog
} // namespace facerobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::facerobot::voiceRecog > {
  static const char* value()
  {
    return "4dbe3fedfe440cb743ba27bf8c422fe7";
  }

  static const char* value(const ::facerobot::voiceRecog&) { return value(); }
};

template<>
struct DataType< ::facerobot::voiceRecog > {
  static const char* value()
  {
    return "facerobot/voiceRecog";
  }

  static const char* value(const ::facerobot::voiceRecog&) { return value(); }
};


// service_traits::MD5Sum< ::facerobot::voiceRecogRequest> should match 
// service_traits::MD5Sum< ::facerobot::voiceRecog > 
template<>
struct MD5Sum< ::facerobot::voiceRecogRequest>
{
  static const char* value()
  {
    return MD5Sum< ::facerobot::voiceRecog >::value();
  }
  static const char* value(const ::facerobot::voiceRecogRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::facerobot::voiceRecogRequest> should match 
// service_traits::DataType< ::facerobot::voiceRecog > 
template<>
struct DataType< ::facerobot::voiceRecogRequest>
{
  static const char* value()
  {
    return DataType< ::facerobot::voiceRecog >::value();
  }
  static const char* value(const ::facerobot::voiceRecogRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::facerobot::voiceRecogResponse> should match 
// service_traits::MD5Sum< ::facerobot::voiceRecog > 
template<>
struct MD5Sum< ::facerobot::voiceRecogResponse>
{
  static const char* value()
  {
    return MD5Sum< ::facerobot::voiceRecog >::value();
  }
  static const char* value(const ::facerobot::voiceRecogResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::facerobot::voiceRecogResponse> should match 
// service_traits::DataType< ::facerobot::voiceRecog > 
template<>
struct DataType< ::facerobot::voiceRecogResponse>
{
  static const char* value()
  {
    return DataType< ::facerobot::voiceRecog >::value();
  }
  static const char* value(const ::facerobot::voiceRecogResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACEROBOT_MESSAGE_VOICERECOG_H
