// Generated by gencpp from file facerobot/voiceRecogRequest.msg
// DO NOT EDIT!


#ifndef FACEROBOT_MESSAGE_VOICERECOGREQUEST_H
#define FACEROBOT_MESSAGE_VOICERECOGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace facerobot
{
template <class ContainerAllocator>
struct voiceRecogRequest_
{
  typedef voiceRecogRequest_<ContainerAllocator> Type;

  voiceRecogRequest_()
    : trigger(false)  {
    }
  voiceRecogRequest_(const ContainerAllocator& _alloc)
    : trigger(false)  {
    }



   typedef uint8_t _trigger_type;
  _trigger_type trigger;




  typedef boost::shared_ptr< ::facerobot::voiceRecogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::facerobot::voiceRecogRequest_<ContainerAllocator> const> ConstPtr;

}; // struct voiceRecogRequest_

typedef ::facerobot::voiceRecogRequest_<std::allocator<void> > voiceRecogRequest;

typedef boost::shared_ptr< ::facerobot::voiceRecogRequest > voiceRecogRequestPtr;
typedef boost::shared_ptr< ::facerobot::voiceRecogRequest const> voiceRecogRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::facerobot::voiceRecogRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::facerobot::voiceRecogRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace facerobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'voice_msg': ['/home/turtlebot/xu_slam/src/voice_msg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::facerobot::voiceRecogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facerobot::voiceRecogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facerobot::voiceRecogRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6d1152a533bdef9ec687318c8e489b0";
  }

  static const char* value(const ::facerobot::voiceRecogRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6d1152a533bdef9ULL;
  static const uint64_t static_value2 = 0xec687318c8e489b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "facerobot/voiceRecogRequest";
  }

  static const char* value(const ::facerobot::voiceRecogRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool trigger\n\
\n\
";
  }

  static const char* value(const ::facerobot::voiceRecogRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct voiceRecogRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::facerobot::voiceRecogRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::facerobot::voiceRecogRequest_<ContainerAllocator>& v)
  {
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACEROBOT_MESSAGE_VOICERECOGREQUEST_H
