// Generated by gencpp from file rplidar_python/rplidar_data.msg
// DO NOT EDIT!


#ifndef RPLIDAR_PYTHON_MESSAGE_RPLIDAR_DATA_H
#define RPLIDAR_PYTHON_MESSAGE_RPLIDAR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rplidar_python
{
template <class ContainerAllocator>
struct rplidar_data_
{
  typedef rplidar_data_<ContainerAllocator> Type;

  rplidar_data_()
    : angle()
    , distance()
    , frame(0)  {
    }
  rplidar_data_(const ContainerAllocator& _alloc)
    : angle(_alloc)
    , distance(_alloc)
    , frame(0)  {
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angle_type;
  _angle_type angle;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distance_type;
  _distance_type distance;

   typedef uint64_t _frame_type;
  _frame_type frame;




  typedef boost::shared_ptr< ::rplidar_python::rplidar_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rplidar_python::rplidar_data_<ContainerAllocator> const> ConstPtr;

}; // struct rplidar_data_

typedef ::rplidar_python::rplidar_data_<std::allocator<void> > rplidar_data;

typedef boost::shared_ptr< ::rplidar_python::rplidar_data > rplidar_dataPtr;
typedef boost::shared_ptr< ::rplidar_python::rplidar_data const> rplidar_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rplidar_python::rplidar_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rplidar_python::rplidar_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rplidar_python

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'rplidar_python': ['/home/turtlebot2/xu_slam/src/rplidar_python/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_python::rplidar_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_python::rplidar_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_python::rplidar_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_python::rplidar_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_python::rplidar_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_python::rplidar_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rplidar_python::rplidar_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97a7b51379956461eb86779dcf5c8916";
  }

  static const char* value(const ::rplidar_python::rplidar_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97a7b51379956461ULL;
  static const uint64_t static_value2 = 0xeb86779dcf5c8916ULL;
};

template<class ContainerAllocator>
struct DataType< ::rplidar_python::rplidar_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rplidar_python/rplidar_data";
  }

  static const char* value(const ::rplidar_python::rplidar_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rplidar_python::rplidar_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] angle\n\
float32[] distance\n\
uint64 frame\n\
";
  }

  static const char* value(const ::rplidar_python::rplidar_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rplidar_python::rplidar_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.distance);
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct rplidar_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rplidar_python::rplidar_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rplidar_python::rplidar_data_<ContainerAllocator>& v)
  {
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
    s << indent << "frame: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPLIDAR_PYTHON_MESSAGE_RPLIDAR_DATA_H
