// Generated by gencpp from file rfid_handle/ClassifiedData.msg
// DO NOT EDIT!


#ifndef RFID_HANDLE_MESSAGE_CLASSIFIEDDATA_H
#define RFID_HANDLE_MESSAGE_CLASSIFIEDDATA_H

#include <ros/service_traits.h>


#include <rfid_handle/ClassifiedDataRequest.h>
#include <rfid_handle/ClassifiedDataResponse.h>


namespace rfid_handle
{

struct ClassifiedData
{

typedef ClassifiedDataRequest Request;
typedef ClassifiedDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClassifiedData
} // namespace rfid_handle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rfid_handle::ClassifiedData > {
  static const char* value()
  {
    return "debecf591fed201ff6091bab1098501c";
  }

  static const char* value(const ::rfid_handle::ClassifiedData&) { return value(); }
};

template<>
struct DataType< ::rfid_handle::ClassifiedData > {
  static const char* value()
  {
    return "rfid_handle/ClassifiedData";
  }

  static const char* value(const ::rfid_handle::ClassifiedData&) { return value(); }
};


// service_traits::MD5Sum< ::rfid_handle::ClassifiedDataRequest> should match 
// service_traits::MD5Sum< ::rfid_handle::ClassifiedData > 
template<>
struct MD5Sum< ::rfid_handle::ClassifiedDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rfid_handle::ClassifiedData >::value();
  }
  static const char* value(const ::rfid_handle::ClassifiedDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rfid_handle::ClassifiedDataRequest> should match 
// service_traits::DataType< ::rfid_handle::ClassifiedData > 
template<>
struct DataType< ::rfid_handle::ClassifiedDataRequest>
{
  static const char* value()
  {
    return DataType< ::rfid_handle::ClassifiedData >::value();
  }
  static const char* value(const ::rfid_handle::ClassifiedDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rfid_handle::ClassifiedDataResponse> should match 
// service_traits::MD5Sum< ::rfid_handle::ClassifiedData > 
template<>
struct MD5Sum< ::rfid_handle::ClassifiedDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rfid_handle::ClassifiedData >::value();
  }
  static const char* value(const ::rfid_handle::ClassifiedDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rfid_handle::ClassifiedDataResponse> should match 
// service_traits::DataType< ::rfid_handle::ClassifiedData > 
template<>
struct DataType< ::rfid_handle::ClassifiedDataResponse>
{
  static const char* value()
  {
    return DataType< ::rfid_handle::ClassifiedData >::value();
  }
  static const char* value(const ::rfid_handle::ClassifiedDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RFID_HANDLE_MESSAGE_CLASSIFIEDDATA_H
