// Generated by gencpp from file rfid_handle/ClassifiedDataRequest.msg
// DO NOT EDIT!


#ifndef RFID_HANDLE_MESSAGE_CLASSIFIEDDATAREQUEST_H
#define RFID_HANDLE_MESSAGE_CLASSIFIEDDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rfid_handle
{
template <class ContainerAllocator>
struct ClassifiedDataRequest_
{
  typedef ClassifiedDataRequest_<ContainerAllocator> Type;

  ClassifiedDataRequest_()
    : rssi(0)
    , ID()  {
    }
  ClassifiedDataRequest_(const ContainerAllocator& _alloc)
    : rssi(0)
    , ID(_alloc)  {
    }



   typedef int16_t _rssi_type;
  _rssi_type rssi;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ID_type;
  _ID_type ID;




  typedef boost::shared_ptr< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifiedDataRequest_

typedef ::rfid_handle::ClassifiedDataRequest_<std::allocator<void> > ClassifiedDataRequest;

typedef boost::shared_ptr< ::rfid_handle::ClassifiedDataRequest > ClassifiedDataRequestPtr;
typedef boost::shared_ptr< ::rfid_handle::ClassifiedDataRequest const> ClassifiedDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rfid_handle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rfid_handle': ['/home/turtlebot2/xu_slam/src/rfid_handle/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8348e5c8cbbd8289ce2ac4e78e331dec";
  }

  static const char* value(const ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8348e5c8cbbd8289ULL;
  static const uint64_t static_value2 = 0xce2ac4e78e331decULL;
};

template<class ContainerAllocator>
struct DataType< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfid_handle/ClassifiedDataRequest";
  }

  static const char* value(const ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 rssi\n\
string ID\n\
";
  }

  static const char* value(const ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rssi);
      stream.next(m.ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ClassifiedDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfid_handle::ClassifiedDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "rssi: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "ID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFID_HANDLE_MESSAGE_CLASSIFIEDDATAREQUEST_H
