// Generated by gencpp from file rfid_handle/probability.msg
// DO NOT EDIT!


#ifndef RFID_HANDLE_MESSAGE_PROBABILITY_H
#define RFID_HANDLE_MESSAGE_PROBABILITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rfid_handle
{
template <class ContainerAllocator>
struct probability_
{
  typedef probability_<ContainerAllocator> Type;

  probability_()
    : probability()  {
    }
  probability_(const ContainerAllocator& _alloc)
    : probability(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _probability_type;
  _probability_type probability;




  typedef boost::shared_ptr< ::rfid_handle::probability_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfid_handle::probability_<ContainerAllocator> const> ConstPtr;

}; // struct probability_

typedef ::rfid_handle::probability_<std::allocator<void> > probability;

typedef boost::shared_ptr< ::rfid_handle::probability > probabilityPtr;
typedef boost::shared_ptr< ::rfid_handle::probability const> probabilityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfid_handle::probability_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfid_handle::probability_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rfid_handle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rfid_handle': ['/home/turtlebot/xu_slam/src/rfid_handle/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rfid_handle::probability_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid_handle::probability_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid_handle::probability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid_handle::probability_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid_handle::probability_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid_handle::probability_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfid_handle::probability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd9bfe66ae445cc5d5c104507b89168d";
  }

  static const char* value(const ::rfid_handle::probability_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd9bfe66ae445cc5ULL;
  static const uint64_t static_value2 = 0xd5c104507b89168dULL;
};

template<class ContainerAllocator>
struct DataType< ::rfid_handle::probability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfid_handle/probability";
  }

  static const char* value(const ::rfid_handle::probability_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfid_handle::probability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string probability\n\
\n\
";
  }

  static const char* value(const ::rfid_handle::probability_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfid_handle::probability_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.probability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct probability_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfid_handle::probability_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfid_handle::probability_<ContainerAllocator>& v)
  {
    s << indent << "probability: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.probability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFID_HANDLE_MESSAGE_PROBABILITY_H
