// Generated by gencpp from file rfid/RFIDreadRow.msg
// DO NOT EDIT!


#ifndef RFID_MESSAGE_RFIDREADROW_H
#define RFID_MESSAGE_RFIDREADROW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rfid
{
template <class ContainerAllocator>
struct RFIDreadRow_
{
  typedef RFIDreadRow_<ContainerAllocator> Type;

  RFIDreadRow_()
    : data()  {
    }
  RFIDreadRow_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::rfid::RFIDreadRow_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfid::RFIDreadRow_<ContainerAllocator> const> ConstPtr;

}; // struct RFIDreadRow_

typedef ::rfid::RFIDreadRow_<std::allocator<void> > RFIDreadRow;

typedef boost::shared_ptr< ::rfid::RFIDreadRow > RFIDreadRowPtr;
typedef boost::shared_ptr< ::rfid::RFIDreadRow const> RFIDreadRowConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfid::RFIDreadRow_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfid::RFIDreadRow_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rfid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'rfid': ['/home/turtlebot2/xu_slam/src/rfid/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rfid::RFIDreadRow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid::RFIDreadRow_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid::RFIDreadRow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid::RFIDreadRow_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid::RFIDreadRow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid::RFIDreadRow_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfid::RFIDreadRow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::rfid::RFIDreadRow_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rfid::RFIDreadRow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfid/RFIDreadRow";
  }

  static const char* value(const ::rfid::RFIDreadRow_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfid::RFIDreadRow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n\
";
  }

  static const char* value(const ::rfid::RFIDreadRow_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfid::RFIDreadRow_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RFIDreadRow_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfid::RFIDreadRow_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfid::RFIDreadRow_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFID_MESSAGE_RFIDREADROW_H
