// Generated by gencpp from file rfid/TransferData.msg
// DO NOT EDIT!


#ifndef RFID_MESSAGE_TRANSFERDATA_H
#define RFID_MESSAGE_TRANSFERDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rfid
{
template <class ContainerAllocator>
struct TransferData_
{
  typedef TransferData_<ContainerAllocator> Type;

  TransferData_()
    : header()
    , rssi(0)
    , ID()  {
    }
  TransferData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rssi(0)
    , ID(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _rssi_type;
  _rssi_type rssi;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ID_type;
  _ID_type ID;




  typedef boost::shared_ptr< ::rfid::TransferData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfid::TransferData_<ContainerAllocator> const> ConstPtr;

}; // struct TransferData_

typedef ::rfid::TransferData_<std::allocator<void> > TransferData;

typedef boost::shared_ptr< ::rfid::TransferData > TransferDataPtr;
typedef boost::shared_ptr< ::rfid::TransferData const> TransferDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfid::TransferData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfid::TransferData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rfid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'rfid': ['/home/turtlebot2/xu_slam/src/rfid/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rfid::TransferData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid::TransferData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid::TransferData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid::TransferData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid::TransferData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid::TransferData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfid::TransferData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68d70907a1877460194ed3fc27b773d8";
  }

  static const char* value(const ::rfid::TransferData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68d70907a1877460ULL;
  static const uint64_t static_value2 = 0x194ed3fc27b773d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rfid::TransferData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfid/TransferData";
  }

  static const char* value(const ::rfid::TransferData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfid::TransferData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 rssi\n\
string ID\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rfid::TransferData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfid::TransferData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rssi);
      stream.next(m.ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TransferData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfid::TransferData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfid::TransferData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rssi: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "ID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFID_MESSAGE_TRANSFERDATA_H
