"""autogenerated by genpy from voice_interface/Get.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Get(genpy.Message):
  _md5sum = "712d3f98ffc20e1bda6fa2b3c9033441"
  _type = "voice_interface/Get"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool get
int64 rencheng2
int64 operation
int64 object2
int64 action

"""
  __slots__ = ['get','rencheng2','operation','object2','action']
  _slot_types = ['bool','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       get,rencheng2,operation,object2,action

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Get, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.get is None:
        self.get = False
      if self.rencheng2 is None:
        self.rencheng2 = 0
      if self.operation is None:
        self.operation = 0
      if self.object2 is None:
        self.object2 = 0
      if self.action is None:
        self.action = 0
    else:
      self.get = False
      self.rencheng2 = 0
      self.operation = 0
      self.object2 = 0
      self.action = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4q.pack(_x.get, _x.rencheng2, _x.operation, _x.object2, _x.action))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.get, _x.rencheng2, _x.operation, _x.object2, _x.action,) = _struct_B4q.unpack(str[start:end])
      self.get = bool(self.get)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4q.pack(_x.get, _x.rencheng2, _x.operation, _x.object2, _x.action))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.get, _x.rencheng2, _x.operation, _x.object2, _x.action,) = _struct_B4q.unpack(str[start:end])
      self.get = bool(self.get)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B4q = struct.Struct("<B4q")
