"""autogenerated by genpy from voice_interface/Send.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Send(genpy.Message):
  _md5sum = "a711c708becf295f2e6df4e6e308b5bd"
  _type = "voice_interface/Send"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool send
int64 song1
int64 object1
int64 dao1
int64 dd
int64 rencheng1


"""
  __slots__ = ['send','song1','object1','dao1','dd','rencheng1']
  _slot_types = ['bool','int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       send,song1,object1,dao1,dd,rencheng1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Send, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.send is None:
        self.send = False
      if self.song1 is None:
        self.song1 = 0
      if self.object1 is None:
        self.object1 = 0
      if self.dao1 is None:
        self.dao1 = 0
      if self.dd is None:
        self.dd = 0
      if self.rencheng1 is None:
        self.rencheng1 = 0
    else:
      self.send = False
      self.song1 = 0
      self.object1 = 0
      self.dao1 = 0
      self.dd = 0
      self.rencheng1 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B5q.pack(_x.send, _x.song1, _x.object1, _x.dao1, _x.dd, _x.rencheng1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.send, _x.song1, _x.object1, _x.dao1, _x.dd, _x.rencheng1,) = _struct_B5q.unpack(str[start:end])
      self.send = bool(self.send)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B5q.pack(_x.send, _x.song1, _x.object1, _x.dao1, _x.dd, _x.rencheng1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.send, _x.song1, _x.object1, _x.dao1, _x.dd, _x.rencheng1,) = _struct_B5q.unpack(str[start:end])
      self.send = bool(self.send)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B5q = struct.Struct("<B5q")
