// Generated by gencpp from file sensor_msg/Cliff_Event.msg
// DO NOT EDIT!


#ifndef SENSOR_MSG_MESSAGE_CLIFF_EVENT_H
#define SENSOR_MSG_MESSAGE_CLIFF_EVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_msg
{
template <class ContainerAllocator>
struct Cliff_Event_
{
  typedef Cliff_Event_<ContainerAllocator> Type;

  Cliff_Event_()
    : bumper(0)
    , state(0)  {
    }
  Cliff_Event_(const ContainerAllocator& _alloc)
    : bumper(0)
    , state(0)  {
    }



   typedef uint8_t _bumper_type;
  _bumper_type bumper;

   typedef uint8_t _state_type;
  _state_type state;


    enum { LEFT = 0u };
     enum { CENTER = 1u };
     enum { RIGHT = 2u };
     enum { BACK = 3u };
     enum { RELEASED = 0u };
     enum { PRESSED = 1u };
 

  typedef boost::shared_ptr< ::sensor_msg::Cliff_Event_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_msg::Cliff_Event_<ContainerAllocator> const> ConstPtr;

}; // struct Cliff_Event_

typedef ::sensor_msg::Cliff_Event_<std::allocator<void> > Cliff_Event;

typedef boost::shared_ptr< ::sensor_msg::Cliff_Event > Cliff_EventPtr;
typedef boost::shared_ptr< ::sensor_msg::Cliff_Event const> Cliff_EventConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_msg::Cliff_Event_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_msg::Cliff_Event_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msg': ['/home/turtlebot/xu_slam/src/sensor_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_msg::Cliff_Event_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_msg::Cliff_Event_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_msg::Cliff_Event_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65d7373d8798a63a14504318204bc7fa";
  }

  static const char* value(const ::sensor_msg::Cliff_Event_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65d7373d8798a63aULL;
  static const uint64_t static_value2 = 0x14504318204bc7faULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msg/Cliff_Event";
  }

  static const char* value(const ::sensor_msg::Cliff_Event_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LEFT=0\n\
uint8 CENTER=1\n\
uint8 RIGHT=2\n\
uint8 BACK=3\n\
\n\
uint8 RELEASED=0\n\
uint8 PRESSED=1\n\
\n\
uint8 bumper\n\
uint8 state\n\
\n\
";
  }

  static const char* value(const ::sensor_msg::Cliff_Event_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bumper);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Cliff_Event_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_msg::Cliff_Event_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_msg::Cliff_Event_<ContainerAllocator>& v)
  {
    s << indent << "bumper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bumper);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MSG_MESSAGE_CLIFF_EVENT_H
