// Generated by gencpp from file web_map/web_odom.msg
// DO NOT EDIT!


#ifndef WEB_MAP_MESSAGE_WEB_ODOM_H
#define WEB_MAP_MESSAGE_WEB_ODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <web_map/ort2D.h>
#include <geometry_msgs/Pose2D.h>

namespace web_map
{
template <class ContainerAllocator>
struct web_odom_
{
  typedef web_odom_<ContainerAllocator> Type;

  web_odom_()
    : orta_pose()
    , pose()  {
    }
  web_odom_(const ContainerAllocator& _alloc)
    : orta_pose(_alloc)
    , pose(_alloc)  {
    }



   typedef  ::web_map::ort2D_<ContainerAllocator>  _orta_pose_type;
  _orta_pose_type orta_pose;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::web_map::web_odom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_map::web_odom_<ContainerAllocator> const> ConstPtr;

}; // struct web_odom_

typedef ::web_map::web_odom_<std::allocator<void> > web_odom;

typedef boost::shared_ptr< ::web_map::web_odom > web_odomPtr;
typedef boost::shared_ptr< ::web_map::web_odom const> web_odomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_map::web_odom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_map::web_odom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace web_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'web_map': ['/home/turtlebot/xu_slam/src/web_map/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::web_map::web_odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_map::web_odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_map::web_odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_map::web_odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_map::web_odom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_map::web_odom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_map::web_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2144b540a38501e83ba7565dedbdbe49";
  }

  static const char* value(const ::web_map::web_odom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2144b540a38501e8ULL;
  static const uint64_t static_value2 = 0x3ba7565dedbdbe49ULL;
};

template<class ContainerAllocator>
struct DataType< ::web_map::web_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_map/web_odom";
  }

  static const char* value(const ::web_map::web_odom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_map::web_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_map/ort2D orta_pose\n\
geometry_msgs/Pose2D pose\n\
\n\
================================================================================\n\
MSG: web_map/ort2D\n\
float32 x\n\
float32 y\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::web_map::web_odom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_map::web_odom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orta_pose);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct web_odom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_map::web_odom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_map::web_odom_<ContainerAllocator>& v)
  {
    s << indent << "orta_pose: ";
    s << std::endl;
    Printer< ::web_map::ort2D_<ContainerAllocator> >::stream(s, indent + "  ", v.orta_pose);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_MAP_MESSAGE_WEB_ODOM_H
