// Generated by gencpp from file tf_nodes/Kill.msg
// DO NOT EDIT!


#ifndef TF_NODES_MESSAGE_KILL_H
#define TF_NODES_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <tf_nodes/KillRequest.h>
#include <tf_nodes/KillResponse.h>


namespace tf_nodes
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace tf_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_nodes::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::tf_nodes::Kill&) { return value(); }
};

template<>
struct DataType< ::tf_nodes::Kill > {
  static const char* value()
  {
    return "tf_nodes/Kill";
  }

  static const char* value(const ::tf_nodes::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::tf_nodes::KillRequest> should match 
// service_traits::MD5Sum< ::tf_nodes::Kill > 
template<>
struct MD5Sum< ::tf_nodes::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::Kill >::value();
  }
  static const char* value(const ::tf_nodes::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::KillRequest> should match 
// service_traits::DataType< ::tf_nodes::Kill > 
template<>
struct DataType< ::tf_nodes::KillRequest>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::Kill >::value();
  }
  static const char* value(const ::tf_nodes::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_nodes::KillResponse> should match 
// service_traits::MD5Sum< ::tf_nodes::Kill > 
template<>
struct MD5Sum< ::tf_nodes::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::Kill >::value();
  }
  static const char* value(const ::tf_nodes::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::KillResponse> should match 
// service_traits::DataType< ::tf_nodes::Kill > 
template<>
struct DataType< ::tf_nodes::KillResponse>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::Kill >::value();
  }
  static const char* value(const ::tf_nodes::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_NODES_MESSAGE_KILL_H
