// Generated by gencpp from file tf_nodes/SetPen.msg
// DO NOT EDIT!


#ifndef TF_NODES_MESSAGE_SETPEN_H
#define TF_NODES_MESSAGE_SETPEN_H

#include <ros/service_traits.h>


#include <tf_nodes/SetPenRequest.h>
#include <tf_nodes/SetPenResponse.h>


namespace tf_nodes
{

struct SetPen
{

typedef SetPenRequest Request;
typedef SetPenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPen
} // namespace tf_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_nodes::SetPen > {
  static const char* value()
  {
    return "9f452acce566bf0c0954594f69a8e41b";
  }

  static const char* value(const ::tf_nodes::SetPen&) { return value(); }
};

template<>
struct DataType< ::tf_nodes::SetPen > {
  static const char* value()
  {
    return "tf_nodes/SetPen";
  }

  static const char* value(const ::tf_nodes::SetPen&) { return value(); }
};


// service_traits::MD5Sum< ::tf_nodes::SetPenRequest> should match 
// service_traits::MD5Sum< ::tf_nodes::SetPen > 
template<>
struct MD5Sum< ::tf_nodes::SetPenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::SetPen >::value();
  }
  static const char* value(const ::tf_nodes::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::SetPenRequest> should match 
// service_traits::DataType< ::tf_nodes::SetPen > 
template<>
struct DataType< ::tf_nodes::SetPenRequest>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::SetPen >::value();
  }
  static const char* value(const ::tf_nodes::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_nodes::SetPenResponse> should match 
// service_traits::MD5Sum< ::tf_nodes::SetPen > 
template<>
struct MD5Sum< ::tf_nodes::SetPenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::SetPen >::value();
  }
  static const char* value(const ::tf_nodes::SetPenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::SetPenResponse> should match 
// service_traits::DataType< ::tf_nodes::SetPen > 
template<>
struct DataType< ::tf_nodes::SetPenResponse>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::SetPen >::value();
  }
  static const char* value(const ::tf_nodes::SetPenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_NODES_MESSAGE_SETPEN_H
