// Generated by gencpp from file tf_nodes/Spawn.msg
// DO NOT EDIT!


#ifndef TF_NODES_MESSAGE_SPAWN_H
#define TF_NODES_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <tf_nodes/SpawnRequest.h>
#include <tf_nodes/SpawnResponse.h>


namespace tf_nodes
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace tf_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_nodes::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::tf_nodes::Spawn&) { return value(); }
};

template<>
struct DataType< ::tf_nodes::Spawn > {
  static const char* value()
  {
    return "tf_nodes/Spawn";
  }

  static const char* value(const ::tf_nodes::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::tf_nodes::SpawnRequest> should match 
// service_traits::MD5Sum< ::tf_nodes::Spawn > 
template<>
struct MD5Sum< ::tf_nodes::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::Spawn >::value();
  }
  static const char* value(const ::tf_nodes::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::SpawnRequest> should match 
// service_traits::DataType< ::tf_nodes::Spawn > 
template<>
struct DataType< ::tf_nodes::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::Spawn >::value();
  }
  static const char* value(const ::tf_nodes::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_nodes::SpawnResponse> should match 
// service_traits::MD5Sum< ::tf_nodes::Spawn > 
template<>
struct MD5Sum< ::tf_nodes::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::Spawn >::value();
  }
  static const char* value(const ::tf_nodes::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::SpawnResponse> should match 
// service_traits::DataType< ::tf_nodes::Spawn > 
template<>
struct DataType< ::tf_nodes::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::Spawn >::value();
  }
  static const char* value(const ::tf_nodes::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_NODES_MESSAGE_SPAWN_H
