// Generated by gencpp from file tf_nodes/SpawnRequest.msg
// DO NOT EDIT!


#ifndef TF_NODES_MESSAGE_SPAWNREQUEST_H
#define TF_NODES_MESSAGE_SPAWNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tf_nodes
{
template <class ContainerAllocator>
struct SpawnRequest_
{
  typedef SpawnRequest_<ContainerAllocator> Type;

  SpawnRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , name()  {
    }
  SpawnRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , name(_alloc)  {
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::tf_nodes::SpawnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_nodes::SpawnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnRequest_

typedef ::tf_nodes::SpawnRequest_<std::allocator<void> > SpawnRequest;

typedef boost::shared_ptr< ::tf_nodes::SpawnRequest > SpawnRequestPtr;
typedef boost::shared_ptr< ::tf_nodes::SpawnRequest const> SpawnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_nodes::SpawnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_nodes::SpawnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tf_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tf_nodes': ['/home/turtlebot/xu_slam/src/tf_nodes/msg'], 'tf': ['/opt/ros/indigo/share/tf/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_nodes::SpawnRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_nodes::SpawnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_nodes::SpawnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57f001c49ab7b11d699f8606c1f4f7ff";
  }

  static const char* value(const ::tf_nodes::SpawnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57f001c49ab7b11dULL;
  static const uint64_t static_value2 = 0x699f8606c1f4f7ffULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_nodes/SpawnRequest";
  }

  static const char* value(const ::tf_nodes::SpawnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 theta\n\
string name\n\
";
  }

  static const char* value(const ::tf_nodes::SpawnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SpawnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_nodes::SpawnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_nodes::SpawnRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_NODES_MESSAGE_SPAWNREQUEST_H
