// Generated by gencpp from file tf_nodes/TeleportRelative.msg
// DO NOT EDIT!


#ifndef TF_NODES_MESSAGE_TELEPORTRELATIVE_H
#define TF_NODES_MESSAGE_TELEPORTRELATIVE_H

#include <ros/service_traits.h>


#include <tf_nodes/TeleportRelativeRequest.h>
#include <tf_nodes/TeleportRelativeResponse.h>


namespace tf_nodes
{

struct TeleportRelative
{

typedef TeleportRelativeRequest Request;
typedef TeleportRelativeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportRelative
} // namespace tf_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_nodes::TeleportRelative > {
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::tf_nodes::TeleportRelative&) { return value(); }
};

template<>
struct DataType< ::tf_nodes::TeleportRelative > {
  static const char* value()
  {
    return "tf_nodes/TeleportRelative";
  }

  static const char* value(const ::tf_nodes::TeleportRelative&) { return value(); }
};


// service_traits::MD5Sum< ::tf_nodes::TeleportRelativeRequest> should match 
// service_traits::MD5Sum< ::tf_nodes::TeleportRelative > 
template<>
struct MD5Sum< ::tf_nodes::TeleportRelativeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::TeleportRelative >::value();
  }
  static const char* value(const ::tf_nodes::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::TeleportRelativeRequest> should match 
// service_traits::DataType< ::tf_nodes::TeleportRelative > 
template<>
struct DataType< ::tf_nodes::TeleportRelativeRequest>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::TeleportRelative >::value();
  }
  static const char* value(const ::tf_nodes::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_nodes::TeleportRelativeResponse> should match 
// service_traits::MD5Sum< ::tf_nodes::TeleportRelative > 
template<>
struct MD5Sum< ::tf_nodes::TeleportRelativeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::TeleportRelative >::value();
  }
  static const char* value(const ::tf_nodes::TeleportRelativeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::TeleportRelativeResponse> should match 
// service_traits::DataType< ::tf_nodes::TeleportRelative > 
template<>
struct DataType< ::tf_nodes::TeleportRelativeResponse>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::TeleportRelative >::value();
  }
  static const char* value(const ::tf_nodes::TeleportRelativeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_NODES_MESSAGE_TELEPORTRELATIVE_H
