// Generated by gencpp from file tf_nodes/TeleportAbsolute.msg
// DO NOT EDIT!


#ifndef TF_NODES_MESSAGE_TELEPORTABSOLUTE_H
#define TF_NODES_MESSAGE_TELEPORTABSOLUTE_H

#include <ros/service_traits.h>


#include <tf_nodes/TeleportAbsoluteRequest.h>
#include <tf_nodes/TeleportAbsoluteResponse.h>


namespace tf_nodes
{

struct TeleportAbsolute
{

typedef TeleportAbsoluteRequest Request;
typedef TeleportAbsoluteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportAbsolute
} // namespace tf_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_nodes::TeleportAbsolute > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::tf_nodes::TeleportAbsolute&) { return value(); }
};

template<>
struct DataType< ::tf_nodes::TeleportAbsolute > {
  static const char* value()
  {
    return "tf_nodes/TeleportAbsolute";
  }

  static const char* value(const ::tf_nodes::TeleportAbsolute&) { return value(); }
};


// service_traits::MD5Sum< ::tf_nodes::TeleportAbsoluteRequest> should match 
// service_traits::MD5Sum< ::tf_nodes::TeleportAbsolute > 
template<>
struct MD5Sum< ::tf_nodes::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::TeleportAbsolute >::value();
  }
  static const char* value(const ::tf_nodes::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::TeleportAbsoluteRequest> should match 
// service_traits::DataType< ::tf_nodes::TeleportAbsolute > 
template<>
struct DataType< ::tf_nodes::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::TeleportAbsolute >::value();
  }
  static const char* value(const ::tf_nodes::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_nodes::TeleportAbsoluteResponse> should match 
// service_traits::MD5Sum< ::tf_nodes::TeleportAbsolute > 
template<>
struct MD5Sum< ::tf_nodes::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_nodes::TeleportAbsolute >::value();
  }
  static const char* value(const ::tf_nodes::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_nodes::TeleportAbsoluteResponse> should match 
// service_traits::DataType< ::tf_nodes::TeleportAbsolute > 
template<>
struct DataType< ::tf_nodes::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return DataType< ::tf_nodes::TeleportAbsolute >::value();
  }
  static const char* value(const ::tf_nodes::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_NODES_MESSAGE_TELEPORTABSOLUTE_H
