"""autogenerated by genpy from web_map/web_odom.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import web_map.msg
import geometry_msgs.msg

class web_odom(genpy.Message):
  _md5sum = "2144b540a38501e83ba7565dedbdbe49"
  _type = "web_map/web_odom"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """web_map/ort2D orta_pose
geometry_msgs/Pose2D pose

================================================================================
MSG: web_map/ort2D
float32 x
float32 y

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['orta_pose','pose']
  _slot_types = ['web_map/ort2D','geometry_msgs/Pose2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       orta_pose,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(web_odom, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.orta_pose is None:
        self.orta_pose = web_map.msg.ort2D()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose2D()
    else:
      self.orta_pose = web_map.msg.ort2D()
      self.pose = geometry_msgs.msg.Pose2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2f3d.pack(_x.orta_pose.x, _x.orta_pose.y, _x.pose.x, _x.pose.y, _x.pose.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.orta_pose is None:
        self.orta_pose = web_map.msg.ort2D()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.orta_pose.x, _x.orta_pose.y, _x.pose.x, _x.pose.y, _x.pose.theta,) = _struct_2f3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2f3d.pack(_x.orta_pose.x, _x.orta_pose.y, _x.pose.x, _x.pose.y, _x.pose.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.orta_pose is None:
        self.orta_pose = web_map.msg.ort2D()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.orta_pose.x, _x.orta_pose.y, _x.pose.x, _x.pose.y, _x.pose.theta,) = _struct_2f3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2f3d = struct.Struct("<2f3d")
