// Generated by gencpp from file speed_handle/speed.msg
// DO NOT EDIT!


#ifndef SPEED_HANDLE_MESSAGE_SPEED_H
#define SPEED_HANDLE_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <speed_handle/Victor.h>
#include <speed_handle/Victor.h>

namespace speed_handle
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : linear()
    , angular()  {
    }
  speed_(const ContainerAllocator& _alloc)
    : linear(_alloc)
    , angular(_alloc)  {
    }



   typedef  ::speed_handle::Victor_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::speed_handle::Victor_<ContainerAllocator>  _angular_type;
  _angular_type angular;




  typedef boost::shared_ptr< ::speed_handle::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speed_handle::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::speed_handle::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::speed_handle::speed > speedPtr;
typedef boost::shared_ptr< ::speed_handle::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speed_handle::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speed_handle::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speed_handle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'speed_handle': ['/home/turtlebot/xu_slam/src/speed_handle/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speed_handle::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speed_handle::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_handle::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_handle::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_handle::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_handle::speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speed_handle::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f195f881246fdfa2798d1d3eebca84a";
  }

  static const char* value(const ::speed_handle::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f195f881246fdfaULL;
  static const uint64_t static_value2 = 0x2798d1d3eebca84aULL;
};

template<class ContainerAllocator>
struct DataType< ::speed_handle::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speed_handle/speed";
  }

  static const char* value(const ::speed_handle::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speed_handle::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Victor linear\n\
Victor angular\n\
\n\
================================================================================\n\
MSG: speed_handle/Victor\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::speed_handle::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speed_handle::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speed_handle::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speed_handle::speed_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::speed_handle::Victor_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::speed_handle::Victor_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEED_HANDLE_MESSAGE_SPEED_H
