(cl:defpackage facerobot-srv
  (:use )
  (:export
   "VOICERECOG"
   "<VOICERECOG-REQUEST>"
   "VOICERECOG-REQUEST"
   "<VOICERECOG-RESPONSE>"
   "VOICERECOG-RESPONSE"
   "SOUND_SYNTHESIS"
   "<SOUND_SYNTHESIS-REQUEST>"
   "SOUND_SYNTHESIS-REQUEST"
   "<SOUND_SYNTHESIS-RESPONSE>"
   "SOUND_SYNTHESIS-RESPONSE"
  ))

